# Generated by Django 3.2.12 on 2022-09-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_url',
            field=models.URLField(default='https://source.unsplash.com/random/?car'),
        ),
    ]
